blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
#    url(r'^comment/(?P<pk>[0-9]+)/approve/$', views.comment_approve, name='comment_approve'),
    path('post/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    
]


urlpatterns += [
    path('fashionblog/', views.fashionblog, name='fashionblog'),
]

urlpatterns += [
    path('post_list/', views.post_list, name='post_list'),
]

urlpatterns += [
    path('contacto/', views.contacto, name='contacto'),
]

projecto1ev/urls.py
"""
mysite URL Configuration
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.home, name='home'),
    # path('about/', views.about, name='about'),
    # path('contacto/', views.contacto, name='contacto'),
    
    path('blog/', include('blog.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    likes = models.IntegerField(default=0)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def _str_(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200) #tiene que estar en la tabla users
    text = models.TextField() #el comentario que yo vaya a escribir
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)
    
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.text

# class Like(models.Model):
#     post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='likes')
#     author = models.CharField(max_length=200) 
#     like = models.IntegerField()


# from django.contrib.auth.models import User

# class Profile(models.Model):
#     """Profile model.

#     Proxy model that extends the base data with other
#     information.
#     """
#     user = models.OneToOneField(User, on_delete=models.PROTECT)

#     website = models.URLField(max_length=200, blank=True)

#     photo = models.ImageField(
#         upload_to='users/pictures',
#         blank=True,
#         null=True
#     )

#     date_modified = models.DateTimeField(auto_now=True)


#     def __str__(self):
#         """Return username."""
#         return self.user.username

blog/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)
        
  
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author','text')
        
        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }

class ContactForm(forms.Form):
    name = forms.CharField(label='Nombre', max_length=100)
    email = forms.EmailField(label='Correo electrónico')
    text = forms.CharField(label='Mensaje', widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.shortcuts import redirect
from .models import Post, Comment
from .forms import PostForm,CommentForm,ContactForm

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):
    Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = post
                comment.save()

            return redirect('post_detail')
    else:
        form = CommentForm()
        comments = Comment.objects.filter(post=pk)
        return render(request, 'blog/post_detail.html', {'post': post, 'form': form, 'comments': comments})

def fashionblog(request):
    return render(request, 'blog/fashionblog.html')

def contacto(request):
    return render(request, 'blog/contacto.html')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            # Enviar correo electrónico o guardar en base de datos
            ...
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form': form})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail', pk=post_pk)

def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('post_list')
    return render(request, 'blog/post_confirm_delete.html', {'post': post})


def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.likes = post.likes + 1 
    post.save()
    return redirect('post_detail', pk=post.pk)

from django.contrib.auth import authenticate, login

def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    posts = Post.objects.all()

    if user is not None:
        login(request, user)
        # Redirect to a success page.
        return render(request, 'blog/post_list.html', {'posts': posts})
    else:
         return redirect('blog/login.html')
        
from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    # Redirect to a success page.

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}<br><br>
<article>
<center>
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
       
    <input value="{{ user }}" type="hidden" name="author" class="form-control" maxlength="200" id="id_author">
  <p>
    <label for="id_text">Text:</label>
    <textarea name="text" cols="40" rows="10" class="form-control" required "id_text"></textarea>
    </p>
        <button type="submit" class="save btn btn-secondary">Send</button>
    </form>
    <center>
    </article>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->  <link rel="stylesheet" href="{% static '../static/css/blog.css' %}">
    {% comment %} <link href="/static/css/blog.css" rel="stylesheet" /> {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
    <link rel="icon" type="image/png" sizes="16x16"  href="/static/img//favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
   
    <style>
        article{
            margin-right: 200px;
            margin-left: 200px
        }
        .comment{
            margin-right: 200px;
            margin-left: 200px
        }
        #contact{
            background-color: black;
        }
    </style>
</head>

<body>
    
      <br><br>
        <nav class="navbar navbar-expand-lg bg-dark text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'post_list' %}"><img width="110em" src="{% static 'img/logoo.png' %}"> </a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-dark text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                                Home
                                <i class="fas fa-bars"></i>
                            </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li type="button" class="btn btn-secondary nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'post_list' %}">MENU</a></li>
                        <li type="button" class="btn btn-secondary nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'fashionblog' %}">NEWS</a></li>
                        <li type="button" class="btn btn-secondary nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'contacto' %}">CONTACT</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle rounded" id="dropdown01" dara-toggle="dropdown">
                                {% if user.is_authenticated %}
                                
                                {{user.get_username}}
                                {%else%}LOGIN{%endif%}
                            </a>
                        <div class="dropdown-menu-dark" aria-labelledby="dropdown01">
                            {%if user.is_authenticated%}
                            <a class="dropdown-item"  href="{% url 'logout' %}?next={{ request.path | urlencode }}">LOGOUT</a>
                            {%else%}
                            <a class="dropdown-item" href="{% url 'login'%}?next={{request.path}}">LOGIN</a>
                            {%endif%}
                        </div>
                        
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
        
        <article class="post">
            <br><br><br><br>
            {% if post.published_date %}
                <time class="date">
                    {{ post.published_date }}
                </time>
            {% endif %}
            <h2 class="bg-white"><strong>{{ post.title }}</strong></h2>
            <p>{{ post.text|linebreaksbr }}</p>
        </article>
        {% block content %}
        {% endblock %}
        
</body>

<footer class="py-3 my-4 bg-dark text-center text-white fixed-bottom opacity-25">
    © 2022 Andrea Cordón Barrionuevo
</footer>
</html>

blog/templates/blog/contacto.html
{% extends 'blog/base.html' %}
{% load static %}

 {% block title %} CONTACT {% endblock %}

    {% block content %}
    
      <section class="about-section text-center" id="contact">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8">
                    
                    <h2 class="text-white mb-4">CONTACT</h2>
                    <p class="text-white-50">
                        Please write us at andrea@moda.com with any questions, concerns, or technical problems.

                        We cannot always write back to everyone, but we promise to read all of our messages.
                    </p>
                </div>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                
                <div  class="text-white-50" class="form-group">
                    <label for="user">User:</label>
                    <input type="text" class="form-control" id="pwuserd">
                  </div>
<br>
                    <div  class="text-white-50" class="form-group">
                      <label for="email">Email address:</label>
                      <input type="email" class="form-control" id="email">
                    </div>
                    <br>
                    <div  class="text-white-50" class="form-group">
                        <label for="pwd">Mesagge:</label>
                        <textarea class="form-control"></textarea>
                      </div>
                    <div  class="text-white-50" class="checkbox">
                      <label><input type="checkbox"> Remember me</label>
                    </div><br>
                    <button type="submit" class="btn btn-secondary">Submit</button>
                    
                  </form>
                  <br>
            
            <img src="{% static 'img/fashion3.webp' %}" alt="fashion" width="900px">
        </div>
    </section>
    <section class="signup-section" id="signup">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-10 col-lg-8 mx-auto text-center">
                    <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                    <h2 class="text-black mb-5">Subscribe to receive updates!</h2>
        
                    <form class="form-signup" id="contactForm" data-sb-form-api-token="API_TOKEN">
                        <!-- Email address input-->
                        <div class="row input-group-newsletter">
                            <div class="col">Limited Time Offer: Subscribe to Vogue and receive two exclusive gifts  <button class="btn btn-primary disabled" id="submitButton" type="submit">SUBSCRIBE ME</button></div>
                        </div>
                    
                      </form><br><br><br>
                </div>
            </div>
        </div>
    </section>
    <section class="contact-section bg-black">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-3 mb-md-0">
                    <div class="card py-4 h-100">
                        <div class="card-body text-center">
                            <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                            <h4 class="text-uppercase m-0">Address</h4>
                            <hr class="my-4 mx-auto" />
                            <div class="small text-black-50">4923 Market Street, Czech Republic</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-3 mb-md-0">
                    <div class="card py-4 h-100">
                        <div class="card-body text-center">
                            <i class="fas fa-envelope text-primary mb-2"></i>
                            <h4 class="text-uppercase m-0">Email</h4>
                            <hr class="my-4 mx-auto" />
                            <div class="small text-black-50"><a href="#!">andrea@moda.com</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-3 mb-md-0">
                    <div class="card py-4 h-100">
                        <div class="card-body text-center">
                            <i class="fas fa-mobile-alt text-primary mb-2"></i>
                            <h4 class="text-uppercase m-0">Phone</h4>
                            <hr class="my-4 mx-auto" />
                            <div class="small text-black-50">+1 (555) 902-8832</div>
                        </div>
                    </div>
                </div>
            </div><br>
            <div class="social d-flex justify-content-center">
                <a class="mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                <a class="mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                <a class="mx-2" href="#!"><i class="fab fa-github"></i></a>
            </div><br><br>
        </div>
    </section>                
{% endblock %}

blog/templates/blog/fashionblog.html
{% extends 'blog/base.html' %}
{% load static %}    
{% block title %} NEWS {% endblock %}
    {% block content %}
    <style>
        body{
            background-image: url('https://i.pinimg.com/564x/67/fa/d0/67fad04f1997dec9aa3702ae5dccb80a.jpg');
            background-size:100%
        }
    </style>
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8"><br><br><br><br><br>
                <h1 class="text-black mb-4">2023 TRENDS</h1><br>
                <p class="text-black-50">
                    With its cameo appearances and celebrity controversy, the spring 2023 ready-to-wear season produced one viral moment after another. Scrollers are gonna scroll, after all. For lasting impact, however, it’s better to look at the clothes that reflect current events. The fight for women’s rights, war, and the environment are dominating the headlines and the best collections reacted to this state of disquietude in a number of ways.
                    <br><br>     </p>
                </div>
        <p class="text-white-50">
        <img src="{% static 'img/fashion4.jpg' %}" alt="fashion" width="500px" height="300px">.........<img src="{% static 'img/fashion3.webp' %}" alt="fashion" width="500px" height="300px"><br><br> <br><br> 
    </p><br><br> </div>   <div class="row gx-4 gx-lg-5 justify-content-center">
     
        <div class="col-lg-8">
            <p class="text-black-50">
                A sense of undoneness was pervasive, and communicated through asymmetric cuts (see all the half skirts) and through distressed and wrinkled fabrics that had the appearance of wear and age. Preparedness is key in the face of unrest, so utilitarian details in the form of hands-free cargo pockets and parachute straps showed up in many collections. Some designers took things a step further, creating defensive armor of sorts for those with the fighting spirit.</h5>
            </p>
        </div> <!-- Projects--> </div>
        </div><br><br>
      <section class="projects-section bg-light" id="projects">
        <div class="container px-4 px-lg-5">
            <!-- Featured Project Row-->
            <div class="row gx-0 mb-4 mb-lg-5 align-items-center">
                <div class="col-xl-8 col-lg-7"><img src="{% static 'img/vintage.webp' %}" alt="fashion" width="600px" height="700px"></div>
                <div class="col-xl-4 col-lg-5">
                    <div class="featured-text text-center text-lg-left">
                        <h4>VINTAGE FASHION</h4>
                        <p class="text-black-50 mb-0">This year, vintage fashion took center stage on the red carpets and in paparazzi shots of celebrities. Whether they were attending a major event or not, Hollywood A-listers made archival fashion feel entirely modern, proving that a well-cut design can stand the test of time.
                          
                            </p>
                    </div>
                </div>
            </div><br><br><br><br>
            <!-- Project One Row-->
            <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
                <div class="col-lg-6"><img src="{% static 'img/fashion.webp' %}" alt="fashion" width="613px" height="300px"></div>
                <div class="col-lg-6">
                    <div class="bg-black text-center h-100 project">
                        <div class="d-flex h-100">
                            <div class="project-text w-100 my-auto text-center text-lg-left">
                                <h4 class="text-white">Misty</h4>
                                <p class="mb-0 text-white-50">An example of where you can put an image of a project, or anything else, along with a description.</p>
                                <hr class="d-none d-lg-block mb-0 ms-0" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Project Two Row-->
            <div class="row gx-0 justify-content-center">
                <div class="col-lg-6"><img src="{% static 'img/fashion4.jpg' %}" alt="fashion" width="522px" height="300px"></div>
                <div class="col-lg-6 order-lg-first">
                    <div class="bg-black text-center h-100 project">
                        <div class="d-flex h-100">
                            <div class="project-text w-100 my-auto text-center text-lg-right">
                                <h4 class="text-white">PUNK COMES BACK!</h4>
                                <p class="mb-0 text-white-50">Another example of a project with its respective description. These sections work well responsively as well, try this theme on a small screen!</p>
                                <hr class="d-none d-lg-block mb-0 me-0" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <br><br>
    <center>
    <img src="{% static 'img/fashion.webp' %}" alt="Texto alternativo">
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
<br><center>
  <h2>Are you sure you want to delete "{{ post.title }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <input class="btn btn-secondary" type="submit" value="CONFIRM">
    <a class="btn btn-alert-primary" href="{% url 'post_detail' post.pk %}">CANCEL</a>
  </form>
</center>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title %} DETAILS {% endblock %}
{% block content %}

    <article class="post">
        <aside class="actions">
            {% if user.is_authenticated %}
            {% if perms.blog.edit_post %}
            <a class="btn btn-secondary" href="{% url 'post_edit' pk=post.pk %}">
              EDIT POST
              </a>
              {%endif%}
        </aside><br>
        <aside class="actions">
            {% if perms.blog.post_delete %}
            <a class="btn btn-secondary" href="{% url 'post_delete' pk=post.pk %}">
              DELETE POST
              </a>
              {%endif%}
        </aside><br>
        {% if perms.blog.add_comment %}
            <a class="btn btn-secondary" href="{% url 'add_comment_to_post' pk=post.pk %}">ADD COMMENT</a>
        {%endif%}
<br><br>
            <h3> <a href="{% url 'post_like' pk=post.pk %}"><i class="fa-solid fa-heart"></i></a>
             Likes: {{post.likes}}  </h3>
<br><hr>
<h2 class="text-center">COMMENTS: {{ post.comments.count  }}</h2>
{% for comment in comments %}
    <hr>
        <article class="comment">
            <div>
                {{ comment.created_date }}
            {% if perms.blog.delete_comment %}
                <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><i class="fa-sharp fa-solid fa-trash"></i></a>
            {%endif%}
            </div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
            {% empty %}
            <p>No comments here yet :(</p>
            <br><br>
        </article>
    
    </article><br><br>

    {% endfor %}
    {% endif %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}<br><br><br>
<style>
    body{
        background-image: url('https://i.pinimg.com/564x/ef/22/75/ef2275cb81992b3fdf28a9229071feaf.jpg');
        background-size:100%
    }
</style>
<center>
    <article >
    <h2>POST:</h2><strong>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
        
    </form>
    <center>
    </strong>
    </article>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block title %} MENU {% endblock %}
{% block content %}
<style>
    body{
        background-image: url('https://i.pinimg.com/564x/ef/22/75/ef2275cb81992b3fdf28a9229071feaf.jpg');
        background-size:100%
    }
</style>
<header class="masthead">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
        <div class="d-flex justify-content-center">
            <div class="text-center"><br>

                <h1 class="text-pink-50" >FASHION BLOG</h1>
                {% if perms.blog.add_post %}
                {% if user.is_authenticated %}
                <a class="btn btn-secondary" href="{% url 'post_new' %}" class="top-menu">
             NEW POST
                </a>
                {% endif %}
            {% endif %}
            </div>
        </div>
    </div>
</header>
    {% for post in posts %}
    <hr>
        <article class="post">
            <time class="date">
                {{ post.published_date }}
            </time>
            <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
      
     Comments: <strong> {{ post.comments.count }} </strong><br>Likes: <strong> {{ post.likes }} </strong>
        </article><br>
     
    {% endfor %}
{% endblock %}